package clases;
// Generated 18-ene-2017 13:39:24 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Historico generated by hbm2java
 */
public class Historico implements java.io.Serializable {

	private String codProf;
	private String nombre;
	private String apellidos;
	private Date fechaAlta;

	public Historico() {
	}

	public Historico(String codProf) {
		this.codProf = codProf;
	}

	public Historico(String codProf, String nombre, String apellidos, Date fechaAlta) {
		this.codProf = codProf;
		this.nombre = nombre;
		this.apellidos = apellidos;
		this.fechaAlta = fechaAlta;
	}

	public String getCodProf() {
		return this.codProf;
	}

	public void setCodProf(String codProf) {
		this.codProf = codProf;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellidos() {
		return this.apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

}
