<?php
	$datos_pilotos = array("Jorge Lorenzo"   =>array(0=> array("Gran Premio"=>"Catar","Posición"=>1,"Puntos"=>25),
													 1=> array("Gran Premio"=>"Americas","Posición"=>3,"Puntos"=>16),
													 2=> array("Gran Premio"=>"España","Posición"=>3,"Puntos"=>16),
													 3=> array("Gran Premio"=>"Francia","Posición"=>7,"Puntos"=>9),
													 4=> array("Gran Premio"=>"Italia","Posición"=>1,"Puntos"=>25),
													 5=> array("Gran Premio"=>"Cataluña","Posición"=>1,"Puntos"=>25),
													 6=> array("Gran Premio"=>"Assen","Posición"=>5,"Puntos"=>11)),
						   "Marc Márquez"    =>array(0=> array("Gran Premio"=>"Catar","Posición"=>3,"Puntos"=>16),
													 1=> array("Gran Premio"=>"Americas","Posición"=>1,"Puntos"=>25),
													 2=> array("Gran Premio"=>"España","Posición"=>2,"Puntos"=>20),
													 3=> array("Gran Premio"=>"Francia","Posición"=>3,"Puntos"=>16),
													 4=> array("Gran Premio"=>"Italia","Posición"=>"Abandono","Puntos"=>0),
													 5=> array("Gran Premio"=>"Cataluña","Posición"=>3,"Puntos"=>16),
													 6=> array("Gran Premio"=>"Assen","Posición"=>2,"Puntos"=>20)),
						   "Dani Pedrosa"    =>array(0=> array("Gran Premio"=>"Catar","Posición"=>1,"Puntos"=>25),
													 1=> array("Gran Premio"=>"Americas","Posición"=>3,"Puntos"=>16),
													 2=> array("Gran Premio"=>"España","Posición"=>3,"Puntos"=>16),
													 3=> array("Gran Premio"=>"Francia","Posición"=>7,"Puntos"=>9),
													 4=> array("Gran Premio"=>"Italia","Posición"=>1,"Puntos"=>25),
													 5=> array("Gran Premio"=>"Cataluña","Posición"=>1,"Puntos"=>25),
													 6=> array("Gran Premio"=>"Assen","Posición"=>5,"Puntos"=>11)),
						   "Valentino Rossi" =>array(0=> array("Gran Premio"=>"Catar","Posición"=>1,"Puntos"=>25),
													 1=> array("Gran Premio"=>"Americas","Posición"=>3,"Puntos"=>16),
													 2=> array("Gran Premio"=>"España","Posición"=>3,"Puntos"=>16),
													 3=> array("Gran Premio"=>"Francia","Posición"=>7,"Puntos"=>9),
													 4=> array("Gran Premio"=>"Italia","Posición"=>1,"Puntos"=>25),
													 5=> array("Gran Premio"=>"Cataluña","Posición"=>1,"Puntos"=>25),
													 6=> array("Gran Premio"=>"Assen","Posición"=>5,"Puntos"=>11)),
						   "Álvaro Bautista" =>array(0=> array("Gran Premio"=>"Catar","Posición"=>1,"Puntos"=>25),
													 1=> array("Gran Premio"=>"Americas","Posición"=>3,"Puntos"=>16),
													 2=> array("Gran Premio"=>"España","Posición"=>3,"Puntos"=>16),
													 3=> array("Gran Premio"=>"Francia","Posición"=>7,"Puntos"=>9),
													 4=> array("Gran Premio"=>"Italia","Posición"=>1,"Puntos"=>25),
													 5=> array("Gran Premio"=>"Cataluña","Posición"=>1,"Puntos"=>25),
													 6=> array("Gran Premio"=>"Assen","Posición"=>5,"Puntos"=>11)),
						   "Héctor Barberá"  =>array(0=> array("Gran Premio"=>"Catar","Posición"=>1,"Puntos"=>25),
													 1=> array("Gran Premio"=>"Americas","Posición"=>3,"Puntos"=>16),
													 2=> array("Gran Premio"=>"España","Posición"=>3,"Puntos"=>16),
													 3=> array("Gran Premio"=>"Francia","Posición"=>7,"Puntos"=>9),
													 4=> array("Gran Premio"=>"Italia","Posición"=>1,"Puntos"=>25),
													 5=> array("Gran Premio"=>"Cataluña","Posición"=>1,"Puntos"=>25),
													 6=> array("Gran Premio"=>"Assen","Posición"=>5,"Puntos"=>11)));
?>