CREATE DEFINER=`root`@`localhost` TRIGGER `ventas`.`producto_BEFORE_UPDATE` BEFORE UPDATE ON `producto` FOR EACH ROW
BEGIN
	IF NEW.idproducto != OLD.idproducto THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR, NO PUEDES CAMBIAR EL IDPRODUCTO';
	END IF;
    
    IF NEW.precio <= 0 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR, EL PRECIO NO PUEDE SER <= 0';
	END IF;
    
    IF NEW.existencias <= 0 THEN
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR, LAS EXISTENCIAS NO PUEDE SER <= 0';
	END IF;
END