CREATE DEFINER=`root`@`localhost` PROCEDURE `Ejercicio07`(fecha DATE)
BEGIN
	DECLARE EXIT HANDLER FOR SQLEXCEPTION
		BEGIN
			SELECT 'Error desconocido';
		END;
	DECLARE CONTINUE HANDLER FOR SQLWARNING BEGIN END;  
    
	SELECT Ejercicio06(fecha);
END