CREATE DEFINER=`root`@`localhost` TRIGGER `ventas`.`oficina_BEFORE_INSERT` BEFORE INSERT ON `oficina` FOR EACH ROW
BEGIN
	SET @contador = @contador + 1;
	IF @contador > 2 THEN 
		SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'ERROR, NO PUEDE REALIZAR MÁS DE DOS INERCIONES SEGUIDAS. ADQUIERA MYSQL PREMIUM POR SOLO 1000000€ al día';
	END IF;
END